language: node_js
node_js:
  - "14.15.1"
# Script que tem que ser executado antes do antes do script "principal"
before_script:
# Pode ser usado npm ou yarn, escolhemos usar yarn.
  - npm ci
# Script "principal"
env:
  global:
    -PORT=8080
    -MONGO=mongodb+srv://TDD:bananinha@cluster0.ttli4.mongodb.net/?retryWrites=true&w=majority
script:
# Script de teste encontrado no package.json
  - npm run test